### ISSUE TITLE
SceneBuilder VS Code path

### ISSUE THREAD

**Issue by SadiyahK** [bilalekremharmansa/SceneBuilderVSCodeExtension#1]
Hello, I am using this extension for the first time and I cannot get VS Code to open scene builder. I think I specified the wrong path to the scenebuilder.exe file and that is why it is not working. If I click 'run with scene builder' nothing happens. However, I cannot find a way to reset the path. I've tried to uninstall and reinstall the extension but this is not working. Is there a way to reset the path? Thank you.

**Comment by bilalekremharmansa** [comment]
Hi,

It's been a while since I developed the extension. It's seems that VSCode get confuses when a workspace is not opened so I published a new version of extension, you can update from VSCode.

Also, you may try to find and remove the config file of the extension in under based on your platform;

`Windows: %APPDATA%\Code\User\workspaceStorage\{HASH}\bilalekrem.scenebuilderextension\settings.json`

`macOS: $HOME/Library/Application Support/Code/User/workspaceStorage/{HASH}/bilalekrem.scenebuilderextension/settings.json`

`Linux: 
$HOME/.config/Code/User/workspaceStorage/{HASH}/bilalekrem.scenebuilderextension/settings.json`

**Comment by stefanteodoropol** [comment]
Hi! I also specified the wrong path in VS Code and couldn't find the correct folder to delete this config.. Finally I did find a settings.json that had only one line, and it was pointing to the wrong SceneBuilder I specified..

The correct path can be set in this file if anyone else is having the same problem:

Windows: %APPDATA%\Local\Programs\Microsoft VS Code\settings.json

Cheers!

**Comment by bilalekremharmansa** [comment]
Hi,

I've published a new version of the extension. 

Please run the following instructions:
Go `Cmd+Alt+P`, 'Configure Scene Builder' thus will be open a window to select Scene Builder executable. Now, you configured the extension.

Open an FXML file and select 'Open in Scene Builder' command in command palette (Cmd+Alt+P).

Hopefully, you should be able to run the extension will no problem.

Feel free for any suggestions.

**Comment by Giftezra** [comment]
hello i also get an error with scene builder could not be opened. please what should I do?
